export const phonesList = [
  {
    id: "d8oqw24asde234234qwexfwfwf22s3OPdcT2",
    title: "Xiaomi MI TV Q1 75 LA4514GL Global",
    brand: "xiaomi",
    price: "1699.99",
    img: "/assets/0169699_lg-tv-55up78003lb_550.webp",
    listImg: [
      "/assets/0169699_lg-tv-55up78003lb_550.webp",
      "/assets/1b.webp",
      "/assets/b3.webp",
      "/assets/b4.webp",
      "/assets/b5.webp",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  // {
  //   id: "d8oqw22345wer33242fwfwf22asdasd3OPdcT2",
  //   title: "Samsung Galaxy S22 Ultra 5G S908E/DS 12/256 Green",
  //   brand: "Samsung",
  //   price: "1799.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0163974_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163974_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163485_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163486_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163486_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "fwef45fw23rw34342asdasdfssd3OPdcT2",
  //   title: "OnePlus 10 Pro 5G 12/256GB Volcanic Black",
  //   brand: "OnePlus",
  //   price: "1399.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0165194_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165194_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165195_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165196_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165194_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "fasdfwef4qwe3r233435rry2asdasdfssd3OPdcT2",
  //   title: "Google Pixel 4 XL Single sim 6GB RAM 64GB LTE w...",
  //   brand: "Google",
  //   price: "699.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109332_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "ffew4546werwerqasdasdfssd3OPdcT2",
  //   title: "Xiaomi Poco X4 GT 5G 8/256GB Blue",
  //   brand: "Xiaomi",
  //   price: "599.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0169801_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169801_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169806_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169804_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169801_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "ffewerwer43432342343sdadasdasdfssd3OPdcT2",
  //   title: "Google Pixel 6A 5G 6/128GB Stormy Black",
  //   brand: "Google",
  //   price: "899.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0171259_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171259_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171260_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171261_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171259_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "d8oqw2wer3434asdefwfwf223OPdcT2",
  //   title: "Apple iPhone 13 Pro | 128GB Silver",
  //   brand: "Apple",
  //   price: "1699.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0154748_apple-iphone-13-pro-128gb-silver_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0154748_apple-iphone-13-pro-128gb-silver_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0154749_apple-iphone-13-pro-128gb-silver_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0154748_apple-iphone-13-pro-128gb-silver_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0154749_apple-iphone-13-pro-128gb-silver_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "d8oqw2wer2345fwfwfwerw22asdasd3OPdcT2",
  //   title: "Samsung Galaxy S22 Ultra 5G S908E/DS 12/256 Green",
  //   brand: "Samsung",
  //   price: "1799.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0163974_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163974_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163485_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163486_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0163486_samsung-galaxy-s22-ultra-5g-s908eds-12256-green_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "fwef45fw2342asdwerwe3asdfssd3OPdcT2",
  //   title: "OnePlus 10 Pro 5G 12/256GB Volcanic Black",
  //   brand: "OnePlus",
  //   price: "1399.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0165194_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165194_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165195_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165196_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0165194_oneplus-10-pro-5g-12256gb-volcanic-black_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "fasdfwef43435rrqwe3242y2asdasdfssd3OPdcT2",
  //   title: "Google Pixel 4 XL Single sim 6GB RAM 64GB LTE w...",
  //   brand: "Google",
  //   price: "699.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109332_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0109333_google-pixel-4-xl-single-sim-6gb-ram-64gb-lte-white_220.png",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "ffew4546asdasdfssdwefwg343OPdcT2",
  //   title: "Xiaomi Poco X4 GT 5G 8/256GB Blue",
  //   brand: "Xiaomi",
  //   price: "599.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0169801_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169801_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169806_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169804_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0169801_xiaomi-poco-x4-gt-5g-8256gb-blue_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
  // {
  //   id: "ffewer2342343sdadasasdadsefwdasdfssd3OPdcT2",
  //   title: "Google Pixel 6A 5G 6/128GB Stormy Black",
  //   brand: "Google",
  //   price: "899.99",
  //   img: "https://img.zoommer.ge/zoommer-images/thumbs/0171259_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //   listImg: [
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171259_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171260_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171261_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //     "https://img.zoommer.ge/zoommer-images/thumbs/0171259_google-pixel-6a-5g-6128gb-stormy-black_220.jpeg",
  //   ],
  //   spec: {
  //     rate: "144 Hz",
  //     type: "intel Core i5",
  //     dpType: "IPS",
  //     ssd: "pCle nVme",
  //   },
  //   amount: 1,
  // },
];

export const tvList = [
  {
    id: "d8oqw24asdeasd234234qwexfsdfsdfsdfsewrvergerewfwf22s3OPdcT2",
    title: "XiaomiQ1 75 LA4514GL Globals",
    brand: "xiaomi",
    price: "1699.99",
    img: "/assets/c1",
    listImg: ["/assets/c1.webp", "/assets/c2.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dasfaasd234234qwexfwfwf22s3OPdcT2",
    title: "Samsung TV QE65Q60CAUXXH-2023",
    brand: "samsung",
    price: "2699.99",
    img: "/assets/d1",
    listImg: ["/assets/d1.webp", "/assets/d2.webp", "/assets/d3.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },

  {
    id: "dasfaasasdad234234qwexfwfwf22s3OPdcT2",
    title: "Samsung TV UE50CU8072UXXH-2023",
    brand: "samsung",
    price: "2399.99",
    img: "/assets/g1",
    listImg: [
      "/assets/g1.webp",
      "/assets/g2.webp",
      "/assets/g3.webp",
      "/assets/g4.webp",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "d8oqw24asde234asd53234qwexfwfwf22s3OPdcT2",
    title: "Xiaomi MI TV Q1 75 LA4514GL Global",
    brand: "xiaomi",
    price: "1699.99",
    img: "/assets/0169699_lg-tv-55up78003lb_550.webp",
    listImg: [
      "/assets/0169699_lg-tv-55up78003lb_550.webp",
      "/assets/1b.webp",
      "/assets/b3.webp",
      "/assets/b4.webp",
      "/assets/b5.webp",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "d8oqw24asdeas243dasd234234qwexfwfwf22s3OPdcT2",
    title: "XiaomiQ1 75 LA4514GL Global",
    brand: "xiaomi",
    price: "1699.99",
    img: "/assets/c1",
    listImg: ["/assets/c1.webp", "/assets/c2.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dasfaasd23423asd34524qwexfwfwf22s3OPdcT2",
    title: "Samsung TV QE65Q60CAUXXH-2023",
    brand: "samsung",
    price: "2699.99",
    img: "/assets/d1",
    listImg: ["/assets/d1.webp", "/assets/d2.webp", "/assets/d3.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dasfaasasdad2asda2434234qwexfwfwf22s3OPdcT2",
    title: "Samsung TV UE50CU8072UXXH-2023",
    brand: "samsung",
    price: "3699.99",
    img: "/assets/F1",
    listImg: ["/assets/F1.webp", "/assets/f2.webp", "/assets/f3.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "daasd324sfaasasdad234234qwexfwfwf22s3OPdcdddT2",
    title: "Samsung TV UE50CU8072UXXH-2023",
    brand: "samsung",
    price: "2399.99",
    img: "/assets/g1",
    listImg: [
      "/assets/g1.webp",
      "/assets/g2.webp",
      "/assets/g3.webp",
      "/assets/g4.webp",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dasfaasasdad2342324asdfaasd4qwexfwfwf22s3OPdcT2",
    title: "Samsung TV UE50CU8072UXXH-2023",
    brand: "samsung",
    price: "3699.99",
    img: "/assets/F1",
    listImg: ["/assets/F1.webp", "/assets/f2.webp", "/assets/f3.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
];

export const laptopsList = [
  {
    id: "d8oqw24asde234sda2234qwexfwfwf22s3OPdcT2",
    title: "Apple MacBook Air 15.3 inch 2023 MQKR3LL/A M2 Chip",
    brand: "apple",
    price: "2699.99",
    img: "/assets/k1.webp",
    listImg: [
      "/assets/k1.webp",
      "/assets/k2.webp",
      "/assets/k3.webp",
      "/assets/k4.webp",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "d8oqw24fwefwef22wf22s3OPdcT2",
    title: "Apple MacBook Air 15.3 inch 2023 MQKR3LL/A M2 Chip",
    brand: "apple",
    price: "3699.99",
    img: "/assets/ap1.webp",
    listImg: ["/assets/ap1.webp", "/assets/ap2.webp", "/assets/ap3.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "d8oqw24fwefasda33wef22wf22s3OPdcT2",
    title: "Apple MacBook Air 15.3 inch 2023 MQKR3LL/A M2 Chip",
    brand: "apple",
    price: "3699.99",
    img: "/assets/pp1.webp",
    listImg: ["/assets/pp1.webp", "/assets/pp2.webp", "/assets/pp3.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "d8cacasvwefasda33wef22wf22s3OPdcT2",
    title: "Apple MacBook Air 15.3 inch 2023 MQKR3LL/A M2 Chip",
    brand: "apple",
    price: "3699.99",
    img: "/assets/gp1.webp",
    listImg: ["/assets/gp1.webp", "/assets/gp2.webp", "/assets/gp.webp"],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
];

export const headphonesList = [
  {
    id: "dr23425ewkl;sdlfsw23sa43ergerOPdcT2",
    title: "Marshall Major IV Bluetooth Black",
    brand: "Marshall",
    price: "139.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0153825_marshall-major-iv-bluetooth-black_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0153826_marshall-major-iv-bluetooth-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0153827_marshall-major-iv-bluetooth-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0153828_marshall-major-iv-bluetooth-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0153829_marshall-major-iv-bluetooth-black_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr234fwewerwzxczxvvbcrwdafew23sa43ergerOPdcT2",
    title: "JBL Tune T510 BT Wireless On-Ear Headphones Blue",
    brand: "JBL",
    price: "49.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0140100_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0140101_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0140102_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0140103_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0140100_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr234fwewerasdfwerwerxzczx43ergerOPdcT2",
    title: "JBL Tune T510 BT Wireless On-Ear Headphones Ros...",
    brand: "JBL",
    price: "69.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0147393_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0147393_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0147394_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0147395_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0147396_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_550.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr234hfghfgjtyjtrwerxzczx43ergerOPdcT2",
    title: "Sony WH-CH510 Wireless Stereo Headset Blue",
    brand: "Sony",
    price: "69.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0127891_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0127890_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0127891_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0127890_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0127891_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr234ergergergererergerOPdcT2",
    title: "Apple AirPods Max Pink",
    brand: "Apple",
    price: "400.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0145986_apple-airpods-max-pink_550.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0145986_apple-airpods-max-pink_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0145984_apple-airpods-max-pink_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0145985_apple-airpods-max-pink_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0145984_apple-airpods-max-pink_550.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },

  {
    id: "dr23asdefweferergerOPdcT2",
    title: "Marshall Major IV Bluetooth Brown",
    brand: "Marshall",
    price: "159.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0170157_marshall-major-iv-bluetooth-brown_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0170158_marshall-major-iv-bluetooth-brown_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0170159_marshall-major-iv-bluetooth-brown_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0170160_marshall-major-iv-bluetooth-brown_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0170161_marshall-major-iv-bluetooth-brown_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23asdefwwegfwefwekjPdcT2",
    title: "JBL JR310 BT Wireless on-ear Headphones Green",
    brand: "JBL",
    price: "59.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0132756_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0132757_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0132758_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0132759_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0136894_jbl-jr310-bt-wireless-on-ear-headphones-green_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23asdefwefekjPweggwdcT2",
    title: "HyperX Cloud II Gaming Headset Red",
    brand: "HyperX",
    price: "99.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0109851_hyperx-cloud-ii-gaming-headset-red_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0109851_hyperx-cloud-ii-gaming-headset-red_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0109852_hyperx-cloud-ii-gaming-headset-red_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0109851_hyperx-cloud-ii-gaming-headset-red_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0109852_hyperx-cloud-ii-gaming-headset-red_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23askjvokdovkfdkjPweggwdcT2",
    title: "JBL JR460 NC BT Wireless on-ear Headphones White",
    brand: "JBL",
    price: "99.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0158086_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0158087_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158086_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158087_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wefwefPweggwdcT2",
    title: "Bose Noise Cancelling Wireless Bluetooth",
    brand: "Bose",
    price: "359.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0146588_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0146585_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0146587_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0146588_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wefwefPwwgweweT2",
    title: "ASUS ROG Delta Core Gaming Headset Type-C Black",
    brand: "ASUS",
    price: "299.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0118350_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0118351_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0118353_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0118355_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wefwefwfewefweffrefPwwgweweT2",
    title: "JBL JR460 NC BT Wireless on-ear Headphones Blue",
    brand: "JBL",
    price: "99.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0158076_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0158076_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158077_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158078_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  /////////////////////////////////////
  {
    id: "dr23425egwegrtrtervxrOPdcT2",
    title: "Marshall Major IV Bluetooth Black",
    brand: "Marshall",
    price: "139.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0153825_marshall-major-iv-bluetooth-black_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0153826_marshall-major-iv-bluetooth-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0153827_marshall-major-iv-bluetooth-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0153828_marshall-major-iv-bluetooth-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0153829_marshall-major-iv-bluetooth-black_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "djyuwjyujydafew23sa43ergerOPdcT2",
    title: "JBL Tune T510 BT Wireless On-Ear Headphones Blue",
    brand: "JBL",
    price: "49.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0140100_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0140101_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0140102_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0140103_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0140100_jbl-tune-t510-bt-wireless-on-ear-headphones-blue_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr234fweregrth5ythfgfrgerOPdcT2",
    title: "JBL Tune T510 BT Wireless On-Ear Headphones Ros...",
    brand: "JBL",
    price: "69.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0147393_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0147393_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0147394_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0147395_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0147396_jbl-tune-t510-bt-wireless-on-ear-headphones-rose-blush_550.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr233453456545df3ergerOPdcT2",
    title: "Sony WH-CH510 Wireless Stereo Headset Blue",
    brand: "Sony",
    price: "69.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0127891_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0127890_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0127891_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0127890_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0127891_sony-wh-ch510-wireless-stereo-headset-blue_550.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr234erger345345ertert45OPdcT2",
    title: "Apple AirPods Max Pink",
    brand: "Apple",
    price: "400.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0145986_apple-airpods-max-pink_550.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0145986_apple-airpods-max-pink_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0145984_apple-airpods-max-pink_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0145985_apple-airpods-max-pink_550.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0145984_apple-airpods-max-pink_550.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },

  {
    id: "dr23asdefweferergertt456544564rtegfdOPdcT2",
    title: "Marshall Major IV Bluetooth Brown",
    brand: "Marshall",
    price: "159.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0170157_marshall-major-iv-bluetooth-brown_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0170158_marshall-major-iv-bluetooth-brown_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0170159_marshall-major-iv-bluetooth-brown_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0170160_marshall-major-iv-bluetooth-brown_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0170161_marshall-major-iv-bluetooth-brown_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23asdefwwtgrtrty562",
    title: "JBL JR310 BT Wireless on-ear Headphones Green",
    brand: "JBL",
    price: "59.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0132756_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0132757_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0132758_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0132759_jbl-jr310-bt-wireless-on-ear-headphones-green_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0136894_jbl-jr310-bt-wireless-on-ear-headphones-green_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23asdefwefekjPweggwdwerwesdcf34cT2",
    title: "HyperX Cloud II Gaming Headset Red",
    brand: "HyperX",
    price: "99.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0109851_hyperx-cloud-ii-gaming-headset-red_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0109851_hyperx-cloud-ii-gaming-headset-red_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0109852_hyperx-cloud-ii-gaming-headset-red_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0109851_hyperx-cloud-ii-gaming-headset-red_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0109852_hyperx-cloud-ii-gaming-headset-red_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23askjvokdsdfsdfrt455ggwdcT2",
    title: "JBL JR460 NC BT Wireless on-ear Headphones White",
    brand: "JBL",
    price: "99.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0158086_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0158087_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158086_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158087_jbl-jr460-nc-bt-wireless-on-ear-headphones-white_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wefwefPweggwdfdfdfgt454w32sdfscT2",
    title: "Bose Noise Cancelling Wireless Bluetooth",
    brand: "Bose",
    price: "359.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0146588_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0146585_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0146587_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0146588_bose-noise-cancelling-wireless-bluetooth-headphones-700-silver_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wefwefPwwgsdfsgffg5354weweT2",
    title: "ASUS ROG Delta Core Gaming Headset Type-C Black",
    brand: "ASUS",
    price: "299.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0118350_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0118351_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0118353_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0118355_asus-rog-delta-core-gaming-headset-type-c-black_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wefweasdasxzc343weffrefPwwgweweT2",
    title: "JBL JR460 NC BT Wireless on-ear Headphones Blue",
    brand: "JBL",
    price: "99.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0158076_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0158076_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158077_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0158078_jbl-jr460-nc-bt-wireless-on-ear-headphones-blue_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
];

export const camerasList = [
  {
    id: "dr23wergrt5545trh3weffrefPwwgweweT2",
    title: "Canon EOS 2000D EF-S 18-55 IS II KIT Black",
    brand: "Canon",
    price: "599.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0092049_canon-eos-2000d-ef-s-18-55-is-ii-kit-black_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0092050_canon-eos-2000d-ef-s-18-55-is-ii-kit-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092051_canon-eos-2000d-ef-s-18-55-is-ii-kit-black_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wergrt5545trh3weffrefrgerghtPwwgweweT2",
    title: "Canon EOS 4000D EF-S 18-55 III KIT Black",
    brand: "Canon",
    price: "509.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0092049_canon-eos-2000d-ef-s-18-55-is-ii-kit-black_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0092050_canon-eos-2000d-ef-s-18-55-is-ii-kit-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092051_canon-eos-2000d-ef-s-18-55-is-ii-kit-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092055_canon-eos-4000d-ef-s-18-55-iii-kit-black_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wergrt554asferferg5trh3weffrefPwwgweweT2",
    title: "Canon EOS 4000D EF-S 18-55 III KIT Black",
    brand: "Canon",
    price: "839.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0149973_canon-eos-m200-ef-m-15-45-is-stm-black_220.jpeg",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0149974_canon-eos-m200-ef-m-15-45-is-stm-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0149975_canon-eos-m200-ef-m-15-45-is-stm-black_220.jpeg",
      "https://img.zoommer.ge/zoommer-images/thumbs/0149976_canon-eos-m200-ef-m-15-45-is-stm-black_220.jpeg",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wergrt554tjyjtyjtyreffrefPwwgweweT2",
    title: "Canon EOS 5D Mark IV Body Black",
    brand: "Canon",
    price: "3469.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0092287_canon-eos-5d-mark-iv-body-black_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0092288_canon-eos-5d-mark-iv-body-black_220.png ",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092289_canon-eos-5d-mark-iv-body-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092290_canon-eos-5d-mark-iv-body-black_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
  {
    id: "dr23wergrt554tjyjtyjtyefsdfewsxcfvfPwwgweweT2",
    title: "Nikon D750 Body Black",
    brand: "Nikon",
    price: "839.99",
    img: "https://img.zoommer.ge/zoommer-images/thumbs/0092067_nikon-d750-body-black_220.png",
    listImg: [
      "https://img.zoommer.ge/zoommer-images/thumbs/0092068_nikon-d750-body-black_220.png ",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092289_canon-eos-5d-mark-iv-body-black_220.png",
      "https://img.zoommer.ge/zoommer-images/thumbs/0092069_nikon-d750-body-black_220.png",
    ],
    spec: {
      rate: "144 Hz",
      type: "intel Core i5",
      dpType: "IPS",
      ssd: "pCle nVme",
    },
    amount: 1,
  },
];
